language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - source venv/bin/activate
  - pip install -r requirements.txt
env:
  - DJANGO_VERSION=1.8.0
# command to run tests
script: python manage test
