language: python

matrix:
    include:
        # use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 3.5
          sudo: false

install:
    - pip install -r requirements.txt

script: python manage.py tests

