##
# This is the travis yml file that travis-ci uses to run the tests.
language: python
python:
  - "3.5.1"

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python manage.py test
